
icnt = "Mesh"
watcher_to_clause_icnt = "Ideal"
watcher_to_clause_type = "Streight"
watcher_to_writer_icnt = "Mesh"
#icnt=ideal,mesh,ring
dram_config = "DDR4"
ideal_l3cache = false
ideal_memory = false
l3_cache_size = 16777216
mems = 8
multi_port = 1
n_clauses = 16
n_watchers = 16
num_writer_entry = 64
num_writer_merge = 8
private_cache_size = 1024
seq = false
single_watcher = false
